disabled_rules:
 - todo
 - force_cast
 - trailing_whitespace
 - vertical_whitespace
excluded:
 - Pods
 - Frameworks
 - Products
 - CountriesOfTheWorldTests
 - CountriesOfTheWorldUITests
 - CountriesOfTheWorld/API.swift
 - R.generated.swift
