target 'CountriesOfTheWorld' do
  use_frameworks!

  pod 'Apollo'
  pod 'SwiftLint'
  pod 'R.swift'

  target 'CountriesOfTheWorldTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CountriesOfTheWorldUITests' do
    # Pods for testing
  end

end
